/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 iphone.gltf 
Author: Valery.Li (https://sketchfab.com/Valery.Li)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/ketchup-001a1969398449e1b9b0dea6c0221505
Title: KETCHUP
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Iphone(props) {
  const { nodes, materials } = useGLTF('/iphone.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.mesh_2__0.geometry} material={materials['Scene_-_Root']} scale={0.001} />
    </group>
  )
}

useGLTF.preload('/iphone.gltf')
