/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ketchap.gltf 
Author: rogerpest (https://sketchfab.com/rogerpest)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/ketch-up-f96a4fb0b5f44219afe401c72ac4d6dd
Title: Ketch Up
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Ketchap(props) {
  const { nodes, materials } = useGLTF('/ketchap.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[-0.017, -0.883, 0.318]} rotation={[-Math.PI / 2, 0, -2.818]} scale={0.003}>
        <group position={[-1.479, 521.406, 106.445]} rotation={[1.309, 0, 0]} scale={10}>
          <mesh geometry={nodes.node_id27_Material_49_0.geometry} material={materials.Material_49} />
          <mesh geometry={nodes.node_id27_Material_49_0_1.geometry} material={materials.Material_49} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/ketchap.gltf')
