/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 mar.gltf 
Author: alban (https://sketchfab.com/alban)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/pizza-ballerina-5a8b58e5de2e47119c5d2187f039b555
Title: Pizza Ballerina
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Mar(props) {
  const { nodes, materials } = useGLTF('/mar.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI, 0, 0.015]} scale={4}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.pizz} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.pizz} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.pizz} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.pizz} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.pizz} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.pizz} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.pizz} />
        <mesh geometry={nodes.Object_9.geometry} material={materials.pizz} />
        <mesh geometry={nodes.Object_10.geometry} material={materials.pizz} />
      </group>
    </group>
  )
}

useGLTF.preload('/mar.gltf')
